### PR TITLE
Add icon to WIT

### PR DESCRIPTION
**Pull request by kwk**
**NOTE: This PR is written against my PR branch that isn't in master yet.**

Fixes https://github.com/almighty/almighty-core/issues/916

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]
lgtm

**Comment by kwk** [comment]
@hectorj2f thank you for reviewing.

**Comment by xcoulon** [comment]
I haven't tested but it looks good to me, too.

**Comment by kwk** [comment]
@xcoulon thank you for reviewing.

**Pull request merged**
